### ISSUE TITLE
version_handler hard coded limit might be bad practice

### ISSUE THREAD

**Issue by Magniler** [aarhusstadsarkiv/acautils#1]
The `get_version()` method currently has a hard-stop coded, where it will recursively call itself a maximum of 6 times. This means that i will look for the `pyproject.toml` file in 6 layers. This should be enough for it to find it, even if it is called deep in a project, but not so many that it risks hitting bedrock. It does this to ensure that no matter where the `get_version()` method is called in a scripts, it is still able to find the .toml file.
Is this an acceptable behaviour? 6 is a bit of a magic number, and might be confusion further down the line

**Comment by clausjuhl** [comment]
Vi designer funktionen så den tager en absolut sti til pyproject.tolm-filen i stedet.
